import sys,os
import json
import subprocess
from Sample import Sample
from pathlib import Path
from configurator import Config
import argparse
import pandas as pd
import numpy as np
from jointCallSampleSheet import retrieve_samples

"""
Generate the WDL samplesheet for given sample.
Give the sample info (obtained from the sampleList generated by getSamples.py) as argument and a config file, optionally
"""
if __name__ == "__main__":
	parser = argparse.ArgumentParser(
		prog = 'singletonSampleSheet.py',
		usage = "python3 %(prog)s [-p family_id -m mother_id -f father_id -l list] [--config config_file (optional)]",	
		description='given a family_id, retrieve the samples included within. Prints them to family_id_sample for future use')
	parser.add_argument('-p', '--proband',help='proband sample name',required=True)
	parser.add_argument('-l', '--list', nargs='?', const='mySampleList.txt', default='mySampleList.txt')
	parser.add_argument('-c', '--config', nargs='?', const='.myconf.json', default='.myconf.json')
	
	args		= parser.parse_args()
	configs  	= Config.from_path(args.config)

	#The paths specific to your configuration should be in the Paths section of the configs
	run_path = configs.Paths.run_path
	sample_sheet_path = configs.Paths.sample_sheet_path

	sample_list = pd.read_csv(args.list,sep=";",names=["Name","Well","Barcode","family_id","Gender","Status","Role","HPO","BAM","Affected"])
	sample_list = sample_list.replace({np.nan: ""})

	sample = retrieve_samples(sample_list, args.proband)
	print(sample)
	sample.write_singleton_samplesheet()
	#Write the list of sample name for this run and the path to their samplesheet
	with open(f"{sample_sheet_path}/{sample.run_id}_samples",'a') as fw:
		fw.write(f"{sample.name},{sample.run_id}_{sample.well}_{sample.name}.json,{sample.bam_path}\n")


